### ISSUE TITLE
partition_html method in unstructured-js-client

### ISSUE THREAD

**Issue by imdoge** [Unstructured-IO/unstructured-js-client#53]
Hello, I'd like to inquire if there is an equivalent method to Python's partition_html in any JavaScript library. The method I'm referring to is from the Python library like so:

from unstructured.partition.html import partition_html

I have reviewed the code and TypeScript type definitions but couldn't find this method.

**Comment by awalker4** [comment]
Hi there, sorry for the delay. Our core library is in python, and our [api](https://github.com/Unstructured-IO/unstructured-api) is a wrapper around the auto partition functionality, which will accept any filetype and call the correct function internally. In order to partition a html file from javascript, you can use the js-client here to send your file to a local instance of unstructured-api, or our [free hosted api](https://unstructured.io/api-key-free).

**Comment by awalker4** [comment]
Let me know if you have any other questions!
